name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build blog with publish.py
        env:
          BASE_URL: /blog/
        run: |
          python publish.py

      - name: Assemble final output to _public
        run: |
          rm -rf _public && mkdir -p _public

          # Blog -> /blog
          mkdir -p _public/blog
          cp -r site/* _public/blog/ 2>/dev/null || true

          # Coming Soon -> /coming-soon  (tự nhận coming-soon/ hoặc coming_soon/)
          if [ -d coming-soon ]; then
            mkdir -p _public/coming-soon
            cp -r coming-soon/* _public/coming-soon/
          elif [ -d coming_soon ]; then
            mkdir -p _public/coming-soon
            cp -r coming_soon/* _public/coming-soon/
          fi

          # Contact -> /contact (nếu có)
          if [ -d contact ]; then
            mkdir -p _public/contact
            cp -r contact/* _public/contact/
          fi

          # Root: redirect về /coming-soon/
          echo '<meta http-equiv="refresh" content="0;url=/coming-soon/">' > _public/index.html

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: cachemissed
          directory: _public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
