name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Tránh deploy chồng lấn khi push liên tục
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Nếu publish.py cần BASE_URL cho blog (ví dụ /blog/), giữ env phía dưới;
      # nếu không cần, có thể bỏ ENV này.
      - name: Build blog with publish.py
        env:
          BASE_URL: /blog/
        run: |
          # Chạy script build blog -> thường tạo ra thư mục 'site/'
          python publish.py || true

      - name: Assemble final output to _public
        run: |
          set -euxo pipefail

          # Xác định nguồn blog: site/ (nếu có file) hoặc _public/blog/ (nếu đã build sẵn)
          BLOG_SRC=""
          if [ -d site ] && [ -n "$(find site -type f | head -1)" ]; then
            BLOG_SRC="site"
          elif [ -d _public/blog ] && [ -n "$(find _public/blog -type f | head -1)" ]; then
            BLOG_SRC="_public/blog"
          fi

          if [ -z "$BLOG_SRC" ]; then
            echo "::error ::Blog build not found (no files in ./site or in _public/blog)"
            exit 1
          fi

          # Chuẩn bị _public và copy nội dung
          rm -rf _public || true
          mkdir -p _public

          if [ "$BLOG_SRC" = "site" ]; then
            mkdir -p _public/blog
            # Không lỗi nếu thư mục rỗng
            shopt -s nullglob dotglob
            cp -r site/* _public/blog/ || true
            shopt -u nullglob dotglob
          else
            # BLOG_SRC đã là _public/blog -> giữ nguyên
            :
          fi

          # Coming Soon -> /coming-soon
          if [ -d coming-soon ]; then
            mkdir -p _public/coming-soon
            shopt -s nullglob dotglob
            cp -r coming-soon/* _public/coming-soon/ || true
            shopt -u nullglob dotglob
          elif [ -d coming_soon ]; then
            mkdir -p _public/coming-soon
            shopt -s nullglob dotglob
            cp -r coming_soon/* _public/coming-soon/ || true
            shopt -u nullglob dotglob
          fi

          # Contact -> /contact (nếu có)
          if [ -d contact ]; then
            mkdir -p _public/contact
            shopt -s nullglob dotglob
            cp -r contact/* _public/contact/ || true
            shopt -u nullglob dotglob
          fi

          # Trang gốc (apex) -> redirect về /coming-soon/
          # Nếu muốn vào blog làm mặc định: đổi /coming-soon/ thành /blog/
          echo '<meta http-equiv="refresh" content="0;url=/coming-soon/">' > _public/index.html

          # Debug liệt kê kết quả build
          echo "== TREE _public =="
          find _public -maxdepth 3 -type f | sed 's/^/_ /'

      # Tùy chọn: upload artifact để kiểm tra nếu cần
      - name: Upload _public artifact (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: _public
          path: _public

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: cachemissed
          directory: _public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
