name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build blog with publish.py (base rỗng)
        run: |
          # KHÔNG set BASE_URL=/blog/ nữa
          python publish.py

      - name: Assemble _public
        run: |
          set -euxo pipefail
          rm -rf _public && mkdir -p _public

          # Blog đã được publish.py xuất ra _public/blog/*  (nếu publish.py của bạn làm khác,
          # thì copy vào _public/blog ở đây)
          if [ ! -d "_public/blog" ]; then
            # Nếu publish.py xuất ra ./site/blog -> copy vào _public/blog
            if [ -d "site/blog" ]; then
              mkdir -p _public/blog
              cp -r site/blog/* _public/blog/
            fi
          fi

          # Coming soon -> _public/coming-soon
          if [ -d coming-soon ]; then
            mkdir -p _public/coming-soon
            cp -r coming-soon/* _public/coming-soon/
          elif [ -d coming_soon ]; then
            mkdir -p _public/coming-soon
            cp -r coming_soon/* _public/coming-soon/
          fi

          # KHÔNG tạo _public/index.html nữa. Functions sẽ rewrite root -> /blog hoặc /coming-soon.

      - name: Show tree (debug)
        run: |
          echo "==== TREE _public ===="
          find _public -maxdepth 3 -type f | sed 's#^_public/##' | sort

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken:  ${{ secrets.CF_API_TOKEN }}
          projectName: cachemissed
          directory: _public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
