name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build blog with publish.py (BASE_URL=/blog/)
        env:
          BASE_URL: /blog/
        run: |
          set -euxo pipefail
          python publish.py
          echo "==== AFTER publish.py ===="
          find . -maxdepth 2 -type d -print
          echo "=== list site/ (nếu có) ==="
          if [ -d site ]; then find site -maxdepth 3 -type f | sed 's/^/  /'; else echo "  (no site/)"; fi
          echo "=== list _public (nếu có) ==="
          if [ -d _public ]; then find _public -maxdepth 3 -type f | sed 's/^/  /'; else echo "  (no _public yet)"; fi

      - name: Assemble final output to _public
        run: |
          set -euxo pipefail
          rm -rf _public
          mkdir -p _public/blog

          # Trường hợp publish.py xuất ra ./site
          if [ -d site ] && [ -n "$(find site -type f | head -1)" ]; then
            rsync -a site/ _public/blog/
            echo "Copied blog from ./site -> _public/blog"
          # Trường hợp publish.py tự ghi thẳng vào _public/blog
          elif [ -d _public/blog ] && [ -n "$(find _public/blog -type f | head -1)" ]; then
            echo "Blog already exists in _public/blog"
          else
            echo "::error ::Blog build not found (no files in ./site or in _public/blog)"
            exit 1
          fi

          # Coming Soon
          if [ -d coming-soon ]; then
            mkdir -p _public/coming-soon
            rsync -a coming-soon/ _public/coming-soon/
          elif [ -d coming_soon ]; then
            mkdir -p _public/coming-soon
            rsync -a coming_soon/ _public/coming-soon/
          fi

          # Contact (nếu có)
          if [ -d contact ]; then
            mkdir -p _public/contact
            rsync -a contact/ _public/contact/
          fi

          # Root redirect -> /coming-soon/
          cat > _public/index.html <<'HTML'
          <!doctype html><meta http-equiv="refresh" content="0;url=/coming-soon/">
          HTML

          echo "=== FINAL _public ==="
          find _public -maxdepth 4 -type f | sort

      - name: Upload _public artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: public-debug
          path: _public
          if-no-files-found: error

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: cachemissed
          directory: _public
          wranglerVersion: '3'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
