name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Build trực tiếp vào _public (publish.py của bạn cần làm việc này)
      - name: Build with publish.py
        env:
          BASE_URL: /
        run: |
          set -euo pipefail
          rm -rf _public
          python publish.py

          # Các file bắt buộc phải có
          test -f _public/blog/index.html
          test -f _public/coming-soon/index.html

          echo '== Sanity check: không được còn marker Jinja trong index.html =='
          ! grep -qE '\{\{|{%' _public/blog/index.html || (echo "ERROR: blog/index.html còn template markers"; exit 1)

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: cachemissed
          directory: _public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
